M3 linreg
UBC-MDS/aRidanalysis pull request #33
Opened 2021-03-10 08:49 UTC by cmmclaug

Heads up that this is draft PR to give a template on some of the stuff I've been working on.

Outstanding questions:
* Do we want to go full mimic of the sklearn interface and deviate from Python?
* As is there are no input assertions yet
* No tests have been written

2021-03-10 23:42 UTC, danielon-5 approved these changes
looks good Craig

2021-03-11 20:12 UTC, ansarusc requested changes
So far so good Craig, some important points:
1. Please add a more step-by-step example on how to use the class instance created.
2. Make sure to combine the initial `assign` methods in a function.
3. In order to mimic sklearn correctly, the function should receive X and y, it would be ideal to remove the initial wrangling and let the used provide his/her clean and tidy X and y

2021-03-12 17:07 UTC, nphaterp reviewed
nice.

2021-03-12 17:07 UTC, nphaterp commented on R/aridanalysis.R
> +  cat_features <- tdf %>%
```suggestion
  cat_features <- df %>% 
```

2021-03-12 17:07 UTC, nphaterp commented on R/aridanalysis.R
> +  numeric_features <- tdf %>%
```suggestion
  numeric_features <- df %>%
```

2021-03-12 17:15 UTC, merged